// Auto-generated by ci-partner skill.
// Run `npx eslint .` to check, `npx eslint . --fix` to auto-fix.

import js from '@eslint/js'
import tseslint from 'typescript-eslint'

{{ESLINT_PLUGINS}}

export default tseslint.config(
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {{ESLINT_TS_CONFIG}}
  {
    rules: {
      {{ESLINT_RULES}}
    },
  },
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/.turbo/**',
    ],
  },
)
